### 2. Exploracion de datos 

### By:
Cristian David Ceballos Velez

### Date:
2026-08-24

### Description:

Una exploración detallada de los datos es esencial antes de proceder a la construcción de modelos. Nos permite detectar y corregir problemas en los datos, entender las distribuciones y relaciones entre variables, y tomar decisiones informadas sobre cómo preprocesar y transformar los datos para el modelado.

## 📚 Import  libraries

In [78]:
from pathlib import Path

import numpy as np
import pandas as pd

## 💾 Load data

In [79]:
DATA_DIR = Path.cwd().resolve().parents[1] / "data" / "01_raw"
df_heart = pd.read_csv(DATA_DIR / "corazon.csv")
df_heart.head()

,age,sex,chest_pain,rest_bp,chol,fbs,rest_ecg,max_hr,exang,old_peak,slope,ca,thal,disease
0,63,Male,typical,145,233,1.0,left ventricular hypertrophy,150,0,2.3,3,0.0,fixed,0
1,67,Male,asymptomatic,160,286,0.0,left ventricular hypertrophy,108,1,1.5,2,3.0,normal,1
2,67,Male,asymptomatic,120,229,0.0,left ventricular hypertrophy,129,1,2.6,2,2.0,reversable,1
3,37,Male,nonanginal,130,250,0.0,normal,187,0,3.5,3,0.0,normal,0
4,41,Female,nontypical,130,204,0.0,left ventricular hypertrophy,172,0,1.4,1,0.0,normal,0

## 👷 Exploración data

In [80]:
df_heart.info()

<class 'pandas.DataFrame'>
RangeIndex: 3030 entries, 0 to 3029
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         3000 non-null   str
 1   sex         2969 non-null   str
 2   chest_pain  2947 non-null   str
 3   rest_bp     2949 non-null   str
 4   chol        2945 non-null   str
 5   fbs         2933 non-null   float64
 6   rest_ecg    2837 non-null   str
 7   max_hr      2859 non-null   str
 8   exang       2879 non-null   str
 9   old_peak    2880 non-null   str
 10  slope       2879 non-null   str
 11  ca          2868 non-null   str
 12  thal        2904 non-null   str
 13  disease     2924 non-null   str
dtypes: float64(1), str(13)
memory usage: 506.9 KB

In [81]:
df_heart.sample(10)

,age,sex,chest_pain,rest_bp,chol,fbs,rest_ecg,max_hr,exang,old_peak,slope,ca,thal,disease
1545,69,Female,typical,140,239,0.0,normal,151,0,1.8,1,2.0,normal,0
778,59,Female,asymptomatic,174,249,0.0,normal,143,1,0.0,2,0.0,normal,1
1942,65,Male,typical,138,282,1.0,left ventricular hypertrophy,174,0,1.4,2,1.0,normal,1
2773,51,Male,nonanginal,110,175,0.0,normal,123,0,0.6,1,0.0,normal,0
983,44,Male,NaN,110,197,0.0,left ventricular hypertrophy,177,0,0.0,1,1.0,normal,1
146,57,Male,asymptomatic,165,289,1.0,left ventricular hypertrophy,124,0,1.0,2,3.0,reversable,1
915,62,Female,asymptomatic,140,268,0.0,left ventricular hypertrophy,160,0,3.6,3,2.0,normal,1
2717,63,Male,asymptomatic,140,187,0.0,left ventricular hypertrophy,144,1,4.0,1,2.0,reversable,1
1008,48,Male,asymptomatic,122,222,0.0,left ventricular hypertrophy,186,0,0.0,1,0.0,NaN,0
2279,60,Male,asymptomatic,140,293,0.0,left ventricular hypertrophy,170,0,1.2,2,2.0,reversable,1

In [82]:
###null values
df_heart = df_heart.replace("?", np.nan)

df_heart.info()

<class 'pandas.DataFrame'>
RangeIndex: 3030 entries, 0 to 3029
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         3000 non-null   str
 1   sex         2969 non-null   str
 2   chest_pain  2947 non-null   str
 3   rest_bp     2949 non-null   str
 4   chol        2945 non-null   str
 5   fbs         2933 non-null   float64
 6   rest_ecg    2837 non-null   str
 7   max_hr      2859 non-null   str
 8   exang       2879 non-null   str
 9   old_peak    2880 non-null   str
 10  slope       2879 non-null   str
 11  ca          2868 non-null   str
 12  thal        2904 non-null   str
 13  disease     2924 non-null   str
dtypes: float64(1), str(13)
memory usage: 506.9 KB

In [83]:
# Assuming your DataFrame is named 'df'
# df = pd.read_csv('your_file.csv')

# Identify numeric and categorical columns
numeric_cols = ["age", "rest_bp", "chol", "max_hr", "old_peak"]
categorical_cols = ["sex", "chest_pain", "disease"]

# Convert numeric columns
df_heart[numeric_cols] = df_heart[numeric_cols].apply(pd.to_numeric, errors="coerce")

# Convert categorical columns
df_heart[categorical_cols] = df_heart[categorical_cols].astype("category")

# Print the updated data types
print(df_heart.dtypes)

age            float64
sex           category
chest_pain    category
rest_bp        float64
chol           float64
fbs            float64
rest_ecg           str
max_hr         float64
exang              str
old_peak       float64
slope              str
ca                 str
thal               str
disease       category
dtype: object

In [84]:
df_heart.info()

<class 'pandas.DataFrame'>
RangeIndex: 3030 entries, 0 to 3029
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         2998 non-null   float64
 1   sex         2969 non-null   category
 2   chest_pain  2947 non-null   category
 3   rest_bp     2947 non-null   float64
 4   chol        2943 non-null   float64
 5   fbs         2933 non-null   float64
 6   rest_ecg    2837 non-null   str
 7   max_hr      2858 non-null   float64
 8   exang       2879 non-null   str
 9   old_peak    2878 non-null   float64
 10  slope       2879 non-null   str
 11  ca          2868 non-null   str
 12  thal        2904 non-null   str
 13  disease     2924 non-null   category
dtypes: category(3), float64(6), str(5)
memory usage: 355.1 KB

In [85]:
# ============================================================
# CLASIFICACIÓN DE VARIABLES DEL DATASET CORAZON
# ============================================================

clasificacion = pd.DataFrame(
    {
        "columna": [
            "age",
            "sex",
            "chest_pain",
            "rest_bp",
            "chol",
            "fbs",
            "rest_ecg",
            "max_hr",
            "exang",
            "old_peak",
            "slope",
            "ca",
            "thal",
            "disease",
        ],
        # ⚠️ Cambiado de df.dtypes a df_heart.dtypes
        "tipo_original": df_heart.dtypes.values.astype(str),
        "tipo_correcto": [
            "int8",
            "category nominal",
            "category nominal",
            "int16",
            "int16",
            "bool",
            "category nominal",
            "int16",
            "bool",
            "float32",
            "category ordinal",
            "Int8 nullable",
            "category nominal",
            "bool",
        ],
        "descripcion": [
            "Edad del paciente",
            "Sexo: Male / Female",
            "Tipo de dolor: typical, nontypical, nonanginal, asymptomatic",
            "Presión arterial en reposo (mm Hg)",
            "Colesterol sérico (mg/dl)",
            "Azúcar en ayunas > 120 mg/dl",
            "Resultados del ECG en reposo",
            "Frecuencia cardíaca máxima alcanzada",
            "Angina inducida por ejercicio",
            "Depresión del ST inducida por ejercicio",
            "Pendiente del ST: 1=ascendente, 2=plana, 3=descendente",
            "Número de vasos coloreados por fluoroscopía (0-3)",
            "Prueba de estrés: normal, fixed, reversable",
            "Diagnóstico de enfermedad cardíaca (target)",
        ],
    }
)

# ============================================================
# CONVERSIÓN DE TIPOS DE DATOS SEGÚN CLASIFICACIÓN
# ============================================================

for _, row in clasificacion.iterrows():
    col = row["columna"]
    tipo = row["tipo_correcto"]

    try:
        if tipo == "bool":
            # Convertir a bool: 1 → True, 0 → False
            df_heart[col] = pd.to_numeric(df_heart[col], errors="coerce").astype("boolean")

        elif tipo.startswith("category"):
            # Convertir a categoría (nominal u ordinal)
            df_heart[col] = df_heart[col].astype("category")

        elif tipo == "Int8 nullable":
            # Entero de 8 bits que admite NaN (mayúscula = nullable)
            df_heart[col] = pd.to_numeric(df_heart[col], errors="coerce").astype("Int8")

        elif tipo.startswith("int"):
            # Primero convertir a float para manejar NaN, luego a Int nullable
            tipo_nullable = tipo.replace("int", "Int")  # int8 → Int8, int16 → Int16
            df_heart[col] = pd.to_numeric(df_heart[col], errors="coerce").astype(tipo_nullable)

        elif tipo.startswith("float"):
            # Convertir a flotante (admite NaN por defecto)
            df_heart[col] = pd.to_numeric(df_heart[col], errors="coerce").astype(tipo)

        print(f"✅ {col:12} → {tipo}")

    except Exception as e:
        print(f"❌ {col:12} → Error: {e}")

# ============================================================
# VERIFICAR TIPOS RESULTANTES
# ============================================================

print("\n--- Tipos de datos después de la conversión ---")
print(df_heart.dtypes)

print("\n--- Clasificación completa ---")
clasificacion["tipo_final"] = df_heart.dtypes.values.astype(str)
clasificacion

✅ age          → int8
✅ sex          → category nominal
✅ chest_pain   → category nominal
✅ rest_bp      → int16
✅ chol         → int16
✅ fbs          → bool
✅ rest_ecg     → category nominal
✅ max_hr       → int16
✅ exang        → bool
✅ old_peak     → float32
✅ slope        → category ordinal
✅ ca           → Int8 nullable
✅ thal         → category nominal
✅ disease      → bool

--- Tipos de datos después de la conversión ---
age               Int8
sex           category
chest_pain    category
rest_bp          Int16
chol             Int16
fbs            boolean
rest_ecg      category
max_hr           Int16
exang          boolean
old_peak       float32
slope         category
ca                Int8
thal          category
disease        boolean
dtype: object

--- Clasificación completa ---

,columna,tipo_original,tipo_correcto,descripcion,tipo_final
0,age,float64,int8,Edad del paciente,Int8
1,sex,category,category nominal,Sexo: Male / Female,category
2,chest_pain,category,category nominal,"Tipo de dolor: typical, nontypical, nonanginal...",category
3,rest_bp,float64,int16,Presión arterial en reposo (mm Hg),Int16
4,chol,float64,int16,Colesterol sérico (mg/dl),Int16
5,fbs,float64,bool,Azúcar en ayunas > 120 mg/dl,boolean
6,rest_ecg,str,category nominal,Resultados del ECG en reposo,category
7,max_hr,float64,int16,Frecuencia cardíaca máxima alcanzada,Int16
8,exang,str,bool,Angina inducida por ejercicio,boolean
9,old_peak,float64,float32,Depresión del ST inducida por ejercicio,float32
10,slope,str,category ordinal,"Pendiente del ST: 1=ascendente, 2=plana, 3=des...",category
11,ca,str,Int8 nullable,Número de vasos coloreados por fluoroscopía (0-3),Int8
12,thal,str,category nominal,"Prueba de estrés: normal, fixed, reversable",category
13,disease,category,bool,Diagnóstico de enfermedad cardíaca (target),boolean

In [86]:
# ============================================================
# ELIMINAR FILAS CON VALORES INVÁLIDOS EN COLUMNAS CATEGÓRICAS
# ============================================================
# Estado actual de los tipos de datos (resultado de clasificacion):
# sex        → category     (ya convertida)
# chest_pain → category     (ya convertida)
# rest_ecg   → str          (pendiente conversión)
# slope      → str          (pendiente conversión)
# thal       → str          (pendiente conversión)
# exang      → str          (pendiente conversión)
# fbs        → float64      (ya numérica)
# disease    → category     (ya convertida)
# ca         → str          (pendiente conversión)
# ============================================================

print("=" * 60)
print("LIMPIEZA DE VALORES INVÁLIDOS EN COLUMNAS CATEGÓRICAS")
print("=" * 60)
print(f"📊 Filas antes de la limpieza: {len(df_heart)}\n")

# ------------------------------------------------------------
# 1. COLUMNAS YA TIPO CATEGORY (sex, chest_pain, disease)
#    Solo verificar que no tengan categorías inválidas
# ------------------------------------------------------------

valores_validos_category = {
    "sex": ["Male", "Female"],
    "chest_pain": ["typical", "nontypical", "nonanginal", "asymptomatic"],
    "disease": [0, 1, True, False],  # ya es boolean/category
}

print("--- Columnas tipo category ---")
for col, validos in valores_validos_category.items():
    # Convertir a str para comparar de forma segura
    mask = ~df_heart[col].astype(str).isin([str(v) for v in validos]) & df_heart[col].notna()
    n = mask.sum()
    print(f"  {'✅' if n == 0 else '❌'} {col:12}: {n:4} filas inválidas eliminadas")
    if n > 0:
        print(f"     Inválidos encontrados: {df_heart.loc[mask, col].unique().tolist()}")
    df_heart = df_heart[~mask].reset_index(drop=True)

# ------------------------------------------------------------
# 2. COLUMNAS TIPO STR (rest_ecg, thal)
#    Validar valores y luego convertir a category
# ------------------------------------------------------------

valores_validos_str = {
    "rest_ecg": [
        "normal",
        "left ventricular hypertrophy",
        "ST-T wave abnormality",
    ],
    "thal": ["normal", "fixed", "reversable"],
}

print("\n--- Columnas tipo str → category ---")
for col, validos in valores_validos_str.items():
    mask = ~df_heart[col].isin(validos) & df_heart[col].notna()
    n = mask.sum()
    print(f"  {'✅' if n == 0 else '❌'} {col:12}: {n:4} filas inválidas eliminadas")
    if n > 0:
        print(f"     Inválidos encontrados: {df_heart.loc[mask, col].unique().tolist()}")
    df_heart = df_heart[~mask].reset_index(drop=True)
    # Convertir a category después de limpiar
    df_heart[col] = df_heart[col].astype("category")
    print(f"     Categorías válidas: {df_heart[col].cat.categories.tolist()}")

# ------------------------------------------------------------
# 3. SLOPE: str → numérico → category ordinal
#    Valores válidos: 1, 2, 3
# ------------------------------------------------------------

print("\n--- Columna slope (str → category ordinal) ---")
df_heart["slope"] = pd.to_numeric(df_heart["slope"], errors="coerce")
mask_slope = ~df_heart["slope"].isin([1.0, 2.0, 3.0])
n_slope = mask_slope.sum()
print(f"  {'✅' if n_slope == 0 else '❌'} slope       : {n_slope:4} filas inválidas eliminadas")
df_heart = df_heart[~mask_slope].reset_index(drop=True)
# Convertir a category ordinal
df_heart["slope"] = pd.Categorical(df_heart["slope"], categories=[1.0, 2.0, 3.0], ordered=True)
print(f"     Categorías: {df_heart['slope'].cat.categories.tolist()} (ordinal)")

# ------------------------------------------------------------
# 4. EXANG: str → bool (0 = No, 1 = Yes)
# ------------------------------------------------------------

print("\n--- Columna exang (str → boolean) ---")
df_heart["exang"] = pd.to_numeric(df_heart["exang"], errors="coerce")
mask_exang = ~df_heart["exang"].isin([0.0, 1.0]) & df_heart["exang"].notna()
n_exang = mask_exang.sum()
print(f"  {'✅' if n_exang == 0 else '❌'} exang       : {n_exang:4} filas inválidas eliminadas")
df_heart = df_heart[~mask_exang].reset_index(drop=True)
df_heart["exang"] = df_heart["exang"].astype("boolean")

# ------------------------------------------------------------
# 5. CA: str → Int8 nullable (valores válidos: 0, 1, 2, 3)
# ------------------------------------------------------------

print("\n--- Columna ca (str → Int8 nullable) ---")
df_heart["ca"] = pd.to_numeric(df_heart["ca"], errors="coerce")
mask_ca = ~df_heart["ca"].isin([0.0, 1.0, 2.0, 3.0]) & df_heart["ca"].notna()
n_ca = mask_ca.sum()
print(f"  {'✅' if n_ca == 0 else '❌'} ca          : {n_ca:4} filas inválidas eliminadas")
df_heart = df_heart[~mask_ca].reset_index(drop=True)
df_heart["ca"] = df_heart["ca"].astype("Int8")

# ============================================================
# RESUMEN FINAL
# ============================================================

print(f"\n{'=' * 60}")
print("RESUMEN FINAL")
print("=" * 60)
print(f"✅ Filas restantes: {len(df_heart)}")
print("\n📋 Tipos de datos finales:")
print(df_heart.dtypes)
print("\n📊 Valores nulos por columna:")
print(df_heart.isnull().sum())

============================================================
LIMPIEZA DE VALORES INVÁLIDOS EN COLUMNAS CATEGÓRICAS
============================================================
📊 Filas antes de la limpieza: 3030

--- Columnas tipo category ---
  ❌ sex         :    3 filas inválidas eliminadas
     Inválidos encontrados: ['2345', '45', '765']
  ❌ chest_pain  :    3 filas inválidas eliminadas
     Inválidos encontrados: ['2345', '2435', '3456']
  ✅ disease     :    0 filas inválidas eliminadas

--- Columnas tipo str → category ---
  ❌ rest_ecg    : 1388 filas inválidas eliminadas
     Inválidos encontrados: ['left ventricular hypertrophy ', '5678', '5653', '36653', '435647']
     Categorías válidas: ['3563', '36653', '435647', '5653', '5678', 'ST-T wave abnormality', 'left ventricular hypertrophy ', 'normal']
  ❌ thal        :    2 filas inválidas eliminadas
     Inválidos encontrados: ['87654', '56']
     Categorías válidas: ['365635463', '53646', '56', '87654', 'fixed', 'normal', 'reversable']

--- Columna slope (str → category ordinal) ---
  ❌ slope       :  149 filas inválidas eliminadas
     Categorías: [1.0, 2.0, 3.0] (ordinal)

--- Columna exang (str → boolean) ---
  ✅ exang       :    0 filas inválidas eliminadas

--- Columna ca (str → Int8 nullable) ---
  ✅ ca          :    0 filas inválidas eliminadas

============================================================
RESUMEN FINAL
============================================================
✅ Filas restantes: 1485

📋 Tipos de datos finales:
age               Int8
sex           category
chest_pain    category
rest_bp          Int16
chol             Int16
fbs            boolean
rest_ecg      category
max_hr           Int16
exang          boolean
old_peak       float32
slope         category
ca                Int8
thal          category
disease        boolean
dtype: object

📊 Valores nulos por columna:
age            4
sex           43
chest_pain    42
rest_bp       44
chol          46
fbs           46
rest_ecg      46
max_hr        23
exang          0
old_peak       2
slope          0
ca            29
thal           9
disease       19
dtype: int64

In [87]:
df_heart.info()

<class 'pandas.DataFrame'>
RangeIndex: 1485 entries, 0 to 1484
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         1481 non-null   Int8
 1   sex         1442 non-null   category
 2   chest_pain  1443 non-null   category
 3   rest_bp     1441 non-null   Int16
 4   chol        1439 non-null   Int16
 5   fbs         1439 non-null   boolean
 6   rest_ecg    1439 non-null   category
 7   max_hr      1462 non-null   Int16
 8   exang       1485 non-null   boolean
 9   old_peak    1483 non-null   float32
 10  slope       1485 non-null   category
 11  ca          1456 non-null   Int8
 12  thal        1476 non-null   category
 13  disease     1466 non-null   boolean
dtypes: Int16(3), Int8(2), boolean(3), category(5), float32(1)
memory usage: 41.9 KB

In [88]:
# ============================================================
# GUARDAR DATASET LIMPIO EN FORMATO PARQUET
# ============================================================

from pathlib import Path

# Definir el directorio de datos
DATA_DIR = Path("../../data")

# Ruta de salida del archivo parquet
output_path = DATA_DIR / "02_intermediate/corazon_type_fixed.parquet"

# Crear el directorio si no existe
output_path.parent.mkdir(parents=True, exist_ok=True)

# Guardar el DataFrame df_heart en formato parquet
df_heart.to_parquet(output_path, index=False)

print(f"✅ Dataset guardado en : {output_path}")
print(f"📁 Tamaño del archivo  : {output_path.stat().st_size / 1024:.1f} KB")
print(f"📊 Filas guardadas     : {len(df_heart)}")
print(f"📋 Columnas guardadas  : {len(df_heart.columns)}")
print("\n--- Tipos de datos guardados ---")
print(df_heart.dtypes)

✅ Dataset guardado en : ../../data/02_intermediate/corazon_type_fixed.parquet
📁 Tamaño del archivo  : 16.1 KB
📊 Filas guardadas     : 1485
📋 Columnas guardadas  : 14

--- Tipos de datos guardados ---
age               Int8
sex           category
chest_pain    category
rest_bp          Int16
chol             Int16
fbs            boolean
rest_ecg      category
max_hr           Int16
exang          boolean
old_peak       float32
slope         category
ca                Int8
thal          category
disease        boolean
dtype: object

Este código realiza los siguientes pasos:

Carga el dataset RAW desde el archivo CSV.
Realiza una descripción general de los datos, mostrando dimensiones, tipos de datos, estadísticas descriptivas y conteo de nulos.
Unifica la representación de valores nulos, convirtiendo tanto los nulos de Pandas como los valores '?' a NaN estándar.
Convierte las columnas a sus tipos de datos adecuados: numéricas a float, categóricas a category, y la columna objetivo a bool.
Explora y corrige problemas en los datos: elimina filas duplicadas y maneja valores atípicos extremos usando el método del rango intercuartil.
Guarda el dataset limpio en formato parquet usando las librerías pyarrow.